# Generated by Django 6.0.6 on 2026-06-11 08:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nurses", "0004_nurseprofile_current_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
                ),
                ("recorded_at", models.DateTimeField()),
                ("accuracy_meters", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_locations",
                        to="nurses.nurseprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["nurse", "recorded_at"], name="tracking_tr_nurse_i_385361_idx"
                    ),
                    models.Index(fields=["recorded_at"], name="tracking_tr_recorde_c32010_idx"),
                ],
            },
        ),
    ]
