# Generated by Django 6.0.6 on 2026-06-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0004_nurseprofile_current_location_and_more"),
        ("requests", "0002_requestoffer"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackinglocation",
            name="care_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_locations",
                to="requests.carerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="trackinglocation",
            index=models.Index(
                fields=["care_request", "recorded_at"], name="tracking_tr_care_re_c3dc46_idx"
            ),
        ),
    ]
