# Generated by Django 6.0.6 on 2026-06-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("JOB_ASSIGNED", "Job assigned"),
                            ("JOB_ACCEPTED", "Job accepted"),
                            ("JOB_WARNING", "Job warning"),
                            ("JOB_CANCELLED", "Job cancelled"),
                            ("NURSE_EN_ROUTE", "Nurse en route"),
                            ("NURSE_ARRIVED", "Nurse arrived"),
                            ("VISIT_STARTED", "Visit started"),
                            ("VISIT_COMPLETED", "Visit completed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("PUSH", "Push"), ("EMAIL", "Email"), ("SMS", "SMS")],
                        default="PUSH",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("resource", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status", "created_at"],
                        name="notificatio_recipie_3f77fb_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["resource", "resource_id"], name="notificatio_resourc_3b1046_idx"
                    ),
                ],
            },
        ),
    ]
