# Generated by Django 6.0.6 on 2026-06-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nurses", "0004_nurseprofile_current_location_and_more"),
        ("patients", "0004_emergencycontact_deleted_at_and_more"),
        ("requests", "0002_requestoffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "care_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rating",
                        to="requests.carerequest",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratings",
                        to="nurses.nurseprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratings",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "created_at"], name="ratings_rat_patient_b62337_idx"
                    ),
                    models.Index(
                        fields=["nurse", "created_at"], name="ratings_rat_nurse_i_09fd1a_idx"
                    ),
                    models.Index(fields=["rating"], name="ratings_rat_rating_f40331_idx"),
                    models.Index(
                        fields=["is_deleted", "deleted_at"], name="ratings_rat_is_dele_7c05aa_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="rating_between_one_and_five",
                    )
                ],
            },
        ),
    ]
