# Generated by Django 6.0.6 on 2026-06-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NurseSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("GENERAL_NURSING", "General nursing"),
                            ("WOUND_CARE", "Wound care"),
                            ("GERIATRIC_CARE", "Geriatric care"),
                            ("PALLIATIVE_CARE", "Palliative care"),
                            ("PEDIATRIC_CARE", "Pediatric care"),
                            ("MIDWIFERY", "Midwifery"),
                            ("MENTAL_HEALTH", "Mental health"),
                            ("ICU_CARE", "ICU care"),
                            ("POST_SURGICAL_CARE", "Post-surgical care"),
                            ("CHRONIC_DISEASE_SUPPORT", "Chronic disease support"),
                        ],
                        db_index=True,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="average_response_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="cancelled_visits_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="completed_visits_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("OTHER", "Other"),
                    ("UNDISCLOSED", "Undisclosed"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="location_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="national_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="nck_license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="nck_license_number",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, upload_to="nurse_profiles/"),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="reputation_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="travel_radius_km",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "10km"), (20, "20km"), (50, "50km"), (100, "100km")], default=10
            ),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="NurseAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="nurses.nurseprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="NurseCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("NCK_LICENSE", "NCK license"),
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT_PHOTO", "Passport photo"),
                            ("ACADEMIC_CERTIFICATE", "Academic certificate"),
                            ("PROFESSIONAL_CERTIFICATE", "Professional certificate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("image", models.ImageField(upload_to="nurse_credentials/")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="nurses.nurseprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_nurse_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="specializations",
            field=models.ManyToManyField(
                blank=True, related_name="nurses", to="nurses.nursespecialization"
            ),
        ),
        migrations.AddIndex(
            model_name="nurseprofile",
            index=models.Index(
                fields=["nck_verification_status", "status", "is_available"],
                name="nurses_nurs_nck_ver_7aaddd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nurseprofile",
            index=models.Index(fields=["travel_radius_km"], name="nurses_nurs_travel__6978ea_idx"),
        ),
        migrations.AddIndex(
            model_name="nurseavailabilityslot",
            index=models.Index(
                fields=["nurse", "day_of_week"], name="nurses_nurs_nurse_i_c72425_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseavailabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="nurse_availability_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseavailabilityslot",
            constraint=models.UniqueConstraint(
                fields=("nurse", "day_of_week", "start_time", "end_time"),
                name="unique_nurse_availability_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="nursecredential",
            index=models.Index(
                fields=["nurse", "credential_type"], name="nurses_nurs_nurse_i_9bd626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nursecredential",
            index=models.Index(
                fields=["verification_status"], name="nurses_nurs_verific_670d56_idx"
            ),
        ),
    ]
