# Generated by Django 6.0.6 on 2026-06-11 08:41

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0003_seed_specializations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nurseprofile",
            name="current_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="nurseprofile",
            index=models.Index(
                fields=["last_location_update"], name="nurses_nurs_last_lo_e555f1_idx"
            ),
        ),
    ]
