# Generated by Django 6.0.6 on 2026-06-11 10:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nurses", "0004_nurseprofile_current_location_and_more"),
        ("patients", "0003_patientprofile_current_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("GENERAL_NURSING", "General nursing"),
                            ("WOUND_CARE", "Wound care"),
                            ("ELDERLY_CARE", "Elderly care"),
                            ("PALLIATIVE_CARE", "Palliative care"),
                            ("POST_SURGERY_CARE", "Post-surgery care"),
                            ("MATERNITY_CARE", "Maternity care"),
                            ("CHRONIC_DISEASE_SUPPORT", "Chronic disease support"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
                ),
                ("requested_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("PREPARING", "Preparing"),
                            ("NURSE_EN_ROUTE", "Nurse en route"),
                            ("ARRIVED", "Arrived"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("journey_started_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("visit_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "assigned_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_care_requests",
                        to="nurses.nurseprofile",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_requests",
                        to="patients.patientdependent",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_requests",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"], name="requests_ca_patient_3af97a_idx"
                    ),
                    models.Index(
                        fields=["assigned_nurse", "status"], name="requests_ca_assigne_529473_idx"
                    ),
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="requests_ca_status_24ae5e_idx",
                    ),
                    models.Index(fields=["requested_time"], name="requests_ca_request_5bd76c_idx"),
                    models.Index(
                        fields=["is_deleted", "deleted_at"], name="requests_ca_is_dele_91ff41_idx"
                    ),
                ],
            },
        ),
    ]
