# Generated by Django 6.0.6 on 2026-06-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("nurses", "0004_nurseprofile_current_location_and_more"),
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OFFERED",
                        max_length=16,
                    ),
                ),
                ("radius_km", models.PositiveSmallIntegerField()),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estimated_travel_time", models.PositiveSmallIntegerField()),
                ("specialization_match", models.BooleanField(default=False)),
                ("rank", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
                (
                    "care_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="requests.carerequest",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_offers",
                        to="notifications.notification",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_offers",
                        to="nurses.nurseprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["care_request", "status"], name="requests_re_care_re_bbb7b6_idx"
                    ),
                    models.Index(fields=["nurse", "status"], name="requests_re_nurse_i_442088_idx"),
                    models.Index(fields=["expires_at"], name="requests_re_expires_328c95_idx"),
                    models.Index(
                        fields=["radius_km", "rank"], name="requests_re_radius__6a6295_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("care_request", "nurse"), name="unique_request_offer_per_nurse"
                    )
                ],
            },
        ),
    ]
