# Generated by Django 6.0.6 on 2026-06-11 07:33

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=apps.common.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="chronic_conditions",
            field=apps.common.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="current_medications",
            field=apps.common.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="disabilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("OTHER", "Other"),
                    ("UNDISCLOSED", "Undisclosed"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="medical_notes",
            field=apps.common.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="national_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="profile_photo",
            field=models.FileField(blank=True, upload_to="patient_profiles/"),
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("relationship", models.CharField(max_length=64)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                            ("UNDISCLOSED", "Undisclosed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("relationship", models.CharField(max_length=64)),
                ("medical_notes", apps.common.fields.EncryptedTextField(blank=True, default="")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
