# Generated by Django 6.0.6 on 2026-06-11 08:41

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientprofile_address_patientprofile_allergies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="current_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["last_location_update"], name="patients_pa_last_lo_ae2169_idx"
            ),
        ),
    ]
