# Generated by Django 6.0.6 on 2026-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientprofile_current_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientdependent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdependent",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["patient", "is_deleted"], name="patients_em_patient_ed0de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["is_deleted", "deleted_at"], name="patients_em_is_dele_aec6cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdependent",
            index=models.Index(
                fields=["patient", "is_deleted"], name="patients_pa_patient_43410b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdependent",
            index=models.Index(
                fields=["is_deleted", "deleted_at"], name="patients_pa_is_dele_890a1b_idx"
            ),
        ),
    ]
