# Generated by Django 6.0.6 on 2026-06-11 11:18

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nurses", "0004_nurseprofile_current_location_and_more"),
        ("patients", "0003_patientprofile_current_location_and_more"),
        ("requests", "0002_requestoffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vitals", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("observations", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("medication_given", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("recommendations", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("follow_up_required", models.BooleanField(default=False)),
                (
                    "follow_up_schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_DAY", "1 day"),
                            ("3_DAYS", "3 days"),
                            ("1_WEEK", "1 week"),
                            ("2_WEEKS", "2 weeks"),
                            ("1_MONTH", "1 month"),
                        ],
                        max_length=16,
                    ),
                ),
                ("follow_up_due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "care_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_note",
                        to="requests.carerequest",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_notes",
                        to="nurses.nurseprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_notes",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "created_at"], name="visits_visi_patient_87b8e0_idx"
                    ),
                    models.Index(
                        fields=["nurse", "created_at"], name="visits_visi_nurse_i_2c6bb1_idx"
                    ),
                    models.Index(
                        fields=["follow_up_required", "follow_up_due_at"],
                        name="visits_visi_follow__54bc3c_idx",
                    ),
                    models.Index(
                        fields=["is_deleted", "deleted_at"], name="visits_visi_is_dele_1520c6_idx"
                    ),
                ],
            },
        ),
    ]
