export {
  useAvailability,
  useChangeAvailability,
  useCreateAvailability,
  useCredentials,
  useDeleteAvailability,
  useNearbyNurses,
  useNckLicenseStatusUrl,
  useNurseProfile,
  useProfileSpecializations,
  useReplaceProfileSpecializations,
  useSpecializations,
  useUpdateAvailability,
  useUpdateNurseProfile,
  useUploadCredential,
} from "@/hooks/useNurses";
